# Generated by Django 3.1.2 on 2020-10-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
