# Generated by Django 3.1.2 on 2020-10-08 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20201008_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='sales.user'),
            preserve_default=False,
        ),
    ]
