# Generated by Django 3.1.2 on 2020-10-08 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_management_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_hotel',
            new_name='is_office',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='user',
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=120)),
                ('first_name', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
