# Generated by Django 3.1.2 on 2020-10-09 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='office',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('activity_date', models.DateField(blank=True)),
                ('activity_time', models.TimeField(blank=True)),
                ('room_number', models.IntegerField()),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('quantity1', models.IntegerField()),
                ('activity1', models.CharField(max_length=254)),
                ('price1', models.IntegerField()),
                ('quantity2', models.IntegerField()),
                ('activity2', models.CharField(max_length=254)),
                ('price2', models.IntegerField()),
                ('quantity3', models.IntegerField()),
                ('activity3', models.CharField(max_length=254)),
                ('price3', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel', to='sales.hotel')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='sales.employee')),
            ],
        ),
    ]
