# Generated by Django 3.1.2 on 2020-10-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20201009_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='activity2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sale',
            name='activity3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price3',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity3',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_cost',
            field=models.IntegerField(blank=True),
        ),
    ]
