# Generated by Django 3.1.2 on 2020-10-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20201009_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
