# Generated by Django 3.1.2 on 2020-10-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20201009_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
