# Generated by Django 3.1.2 on 2020-10-10 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_sale_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='activity1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity1', to='sales.activity'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='activity2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity2', to='sales.activity'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='activity3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity3', to='sales.activity'),
        ),
    ]
