# Generated by Django 3.1.2 on 2020-10-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_sale_concessionaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='concessionaire',
        ),
    ]
