# Generated by Django 3.1.2 on 2020-10-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_sale_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
