# Generated by Django 3.1.2 on 2020-10-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20201012_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=254)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
