# Generated by Django 3.1.2 on 2020-10-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_dayendreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayendreport',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
