# Generated by Django 3.1.2 on 2020-10-14 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_dayendreport_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayendreport',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_report', to='sales.hotel'),
        ),
    ]
