# Generated by Django 3.1.2 on 2020-10-15 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_dayendreport_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayendreport',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
