# Generated by Django 3.1.2 on 2020-10-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_dayendreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayendreport',
            name='other',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
